name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, Thank you for submitting the issue, I will look into it and get back to at the earliest'
        pr-message: 'Hi, Thank you for submitting the PR, please make sure to provide details of the changes being made.'
